sudo: false
language: bash
os:
  - linux

script:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - mv arduino-1.6.5 $HOME/arduino_ide
  - export PATH="$HOME/arduino_ide:$PATH"
  - which arduino
  - mkdir RaspberryPi
  - cd RaspberryPi
  - ln -s $TRAVIS_BUILD_DIR PiDuino
  - cd PiDuino/tools
  - wget http://static.ficeto.com/arm-linux-gnueabihf-linux64.tar.gz
  - tar zxvf arm-linux-gnueabihf-linux64.tar.gz
  - chmod +x arm-linux-gnueabihf/bin/*
  - chmod +x arm-linux-gnueabihf/arm-linux-gnueabihf/bin/*
  - source $TRAVIS_BUILD_DIR/travis/common.sh
  - arduino --board RaspberryPi:PiDuino:bplus --save-prefs
  - arduino --get-pref sketchbook.path
  - build_sketches arduino $HOME/Arduino/libraries/ESPAsyncTCP PiDuino

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/46eabf7ad1d622bcd8cc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
